kind: pipeline
type: docker
name: default

steps:
- name: formatting
  image: rust:1.44.1-slim
  commands:
  - rustup component add rustfmt --toolchain 1.44.1-x86_64-unknown-linux-gnu
  - cargo fmt -- --check

- name: check
  image: rust:1.44.1-slim
  commands:
  - cargo check --verbose

- name: test
  image: rust:1.44.1-slim
  commands:
  - cargo test --verbose
